apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: santhosh8119/my-app:9f348586eaeee8a619d53a0e3633d65f271012d7
        ports:
        - containerPort: 3000


