apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: santhosh8119/my-app:e8702e3d767443655fa74e9db14800b7555cdfcc
        ports:
        - containerPort: 3000


