apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: santhosh8119/my-app:1fe2111b49195fab1a47f4e47a34012a941384bf
        ports:
        - containerPort: 3000


