apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: santhosh8119/my-app:892ad63ae9290d9575cf93d3307d119a6f6e67fc
        ports:
        - containerPort: 3000


